# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'D2D' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for D2D


  target 'D2DTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'D2DUITests' do
    # Pods for testing
  end

end
